### ISSUE TITLE
JDBC: cannot select BLOB columns

### ISSUE THREAD

**Issue by bluezio** [cwida/duckdb#1090]
I have tried to write a SELECT query which mentions a BLOB column, among others. However, I receive the following error:

```
2020-11-07 15:18:25 [main] ERROR DuckNode - Could not fetch property d on node 1
java.sql.SQLException: Unsupported result column type BLOB
	at org.duckdb.DuckDBNative.duckdb_jdbc_fetch(Native Method) ~[na:na]
	at org.duckdb.DuckDBResultSet.<init>(DuckDBResultSet.java:45) ~[na:na]
	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:90) ~[na:na]
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:100) ~[na:na]
	at org.eclipse.hawk.duckdb.DuckNode.getProperty(DuckNode.java:252) ~[na:na]
```

Should I be casting that column to a VARCHAR instead?

**Comment by hannesmuehleisen** [comment]
This simply has not been implemented yet. We should probably do that.

**Comment by bluezio** [comment]
I can work around this by doing a cast and decoding with Commons Codec, but yes, it'd be ideal if we could just call `getBlob`.

**Comment by hannesmuehleisen** [comment]
happy to review a PR ^^

**Comment by Antauri** [comment]
@bluezio how are you working around this, if you can share some pointers.

**Comment by Antauri** [comment]
Not documented on the site, but found the base64 function which can be used as an workaround for blobs (returned as strings). Here's a quick hint on how to do that (we have some JSON encoded as Smile in a column of the Parquet file).

```CREATE TABLE inmemory AS SELECT id, base64(data) as payload FROM '/somewhere/to/your/data.gz.parquet'```

Followed by commons codec decoding and Smile's readTree:
```		
		String queryStatement = "SELECT * FROM inmemory LIMIT 10";
		PreparedStatement preparedQuery = duckConnection.prepareStatement (queryStatement);
		ResultSet querySet = preparedQuery.executeQuery ();
		querySet.next ();
		SmileMapper smileMapper = new SmileMapper ();
		byte[] asBase64 = org.apache.commons.codec.binary.Base64.decodeBase64 (querySet.getString ("payload"));
		JsonNode asJsonNode = smileMapper.readTree (asBase64);
```
Probably for performance reasons the `getBlob` would avoid this Base64 step. Until that's implemented, it's a quirky work-around :)

**Comment by hannesmuehleisen** [comment]
Going to have a go at this

**Comment by Antauri** [comment]
:heart: anxiously anticipating! Thank you kind sir!
