### ISSUE TITLE
Unable to install from tarball

### ISSUE THREAD

**Issue by jonringer** [cwida/duckdb#1196]
When attempting to install from the tar.gz, the setup.py tries to look at the git history to determine a suffix. However, the git history  is not available in a tarball:
```
building
Executing setuptoolsBuildPhase
Traceback (most recent call last):
  File "nix_run_setup", line 8, in <module>
    exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
  File "setup.py", line 85, in <module>
    (source_list, include_list, original_sources) = package_build.build_package(os.path.join(script_path, 'duckdb'))
  File "/private/tmp/nix-build-python3.7-duckdb-0.2.3.drv-0/source/tools/pythonpkg/../../scripts/package_build.py", line 133, in build_package
    githash = git_commit_hash()
  File "/private/tmp/nix-build-python3.7-duckdb-0.2.3.drv-0/source/tools/pythonpkg/../../scripts/package_build.py", line 70, in git_commit_hash
    return subprocess.check_output(['false','log','-1','--format=%h']).strip().decode('utf8')
  File "/nix/store/1zgzhh71ivf4bc322l6vhlb6m9wlaq8k-python3-3.7.9/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/nix/store/1zgzhh71ivf4bc322l6vhlb6m9wlaq8k-python3-3.7.9/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['false', 'log', '-1', '--format=%h']' returned non-zero exit status 1.
```

I would recommend looking at https://pypi.org/project/setuptools-scm/ which allows for something similar, but also allows for package maintainers to determine the version as well with `SETUPTOOLS_SCM_PRETEND_VERSION`

related package PR: https://github.com/NixOS/nixpkgs/pull/105862

**Comment by Mytherin** [comment]
Thanks for the report!

We actually use setuptools-scm for managing our Python versions, but have recently added machinery to get versions for other clients as well (R/JS/Shell). That seems to be breaking here.

I've fixed this in #1197, and also working on adding a CI test so it doesn't break again in the future.

**Comment by Mytherin** [comment]
This should be fixed now in the master. Do you need us to create a new release so the bot picks it up?

**Comment by jonringer** [comment]
that would be great if you could do a patch release

**Comment by jonringer** [comment]
but no rush, the update bot should be able to pick it up eventually

**Comment by hannesmuehleisen** [comment]
New release is out
