### ISSUE TITLE
Segment Fault Crash when select a view (which has IN statement)

### ISSUE THREAD

**Issue by Baoqi** [cwida/duckdb#1427]
For latest master branch (including 0.2.4 release), when I execute the following 2 sql, duckdb will crash with  segment fault error.

```
create view t1 as select * from (select 123 as a) t where a in (select 123 );

select * from t1
```

the call stack for this crash will be:

```
=================================================================
==70572==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffee1d00788 at pc 0x00010ec0ccba bp 0x7ffee1cfe630 sp 0x7ffee1cfe628
READ of size 8 at 0x7ffee1d00788 thread T0
    #0 0x10ec0ccb9 in duckdb::Binder::GenerateTableIndex() binder.cpp:221
    #1 0x10ec0cd48 in duckdb::Binder::GenerateTableIndex() binder.cpp:222
    #2 0x10e7815d9 in duckdb::PlanUncorrelatedSubquery(duckdb::Binder&, duckdb::BoundSubqueryExpression&, std::__1::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator> >&, std::__1::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator> >) plan_subquery.cpp:115
    #3 0x10e77be59 in duckdb::Binder::PlanSubquery(duckdb::BoundSubqueryExpression&, std::__1::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator> >&) plan_subquery.cpp:308
    #4 0x10e76e5b3 in duckdb::Binder::PlanSubqueries(std::__1::unique_ptr<duckdb::Expression, std::__1::default_delete<duckdb::Expression> >*, std::__1::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator> >*) plan_subquery.cpp:340
    #5 0x10e76d77a in duckdb::Binder::PlanFilter(std::__1::unique_ptr<duckdb::Expression, std::__1::default_delete<duckdb::Expression> >, std::__1::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator> >) plan_select_node.cpp:12
    #6 0x10e76f5b5 in duckdb::Binder::CreatePlan(duckdb::BoundSelectNode&) plan_select_node.cpp:30
    #7 0x10ec06a03 in duckdb::Binder::CreatePlan(duckdb::BoundQueryNode&) binder.cpp:109
    #8 0x10e9be930 in duckdb::Binder::CreatePlan(duckdb::BoundSubqueryRef&) plan_subqueryref.cpp:10
    #9 0x10ec08a38 in duckdb::Binder::CreatePlan(duckdb::BoundTableRef&) binder.cpp:157
    #10 0x10e76f0a6 in duckdb::Binder::CreatePlan(duckdb::BoundSelectNode&) plan_select_node.cpp:21
    #11 0x10ec06a03 in duckdb::Binder::CreatePlan(duckdb::BoundQueryNode&) binder.cpp:109
    #12 0x10ec05d4f in duckdb::Binder::Bind(duckdb::QueryNode&) binder.cpp:102
    #13 0x10e84da53 in duckdb::Binder::Bind(duckdb::SelectStatement&) bind_select.cpp:9
    #14 0x10ec02260 in duckdb::Binder::Bind(duckdb::SQLStatement&) binder.cpp:33
    #15 0x10ec2913a in duckdb::Planner::CreatePlan(duckdb::SQLStatement&) planner.cpp:29
    #16 0x10ec2ef98 in duckdb::Planner::CreatePlan(std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) planner.cpp:160
    #17 0x11289d076 in duckdb::ClientContext::CreatePreparedStatement(duckdb::ClientContextLock&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) client_context.cpp:153
    #18 0x112a29dc9 in duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0::operator()() const client_context.cpp:270
    #19 0x112a299f6 in decltype(std::__1::forward<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0&>(fp)()) std::__1::__invoke<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0&>(duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0&) type_traits:4361
    #20 0x112a29856 in void std::__1::__invoke_void_return_wrapper<void>::__call<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0&>(duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0&) __functional_base:349
    #21 0x112a297b2 in std::__1::__function::__alloc_func<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0, std::__1::allocator<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0>, void ()>::operator()() functional:1527
    #22 0x112a23806 in std::__1::__function::__func<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0, std::__1::allocator<duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >)::$_0>, void ()>::operator()() functional:1651
    #23 0x112a42864 in std::__1::__function::__value_func<void ()>::operator()() const functional:1799
    #24 0x1128c0ec2 in std::__1::function<void ()>::operator()() const functional:2347
    #25 0x1128a81dc in duckdb::ClientContext::RunFunctionInTransactionInternal(duckdb::ClientContextLock&, std::__1::function<void ()> const&, bool) client_context.cpp:669
    #26 0x1128a77b6 in duckdb::ClientContext::PrepareInternal(duckdb::ClientContextLock&, std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) client_context.cpp:269
    #27 0x1128a93af in duckdb::ClientContext::Prepare(std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) client_context.cpp:280
    #28 0x1128ca2c8 in duckdb::Connection::Prepare(std::__1::unique_ptr<duckdb::SQLStatement, std::__1::default_delete<duckdb::SQLStatement> >) connection.cpp:80
    #29 0x10e030bf7 in sqlite3_prepare_v2 sqlite3_api_wrapper.cpp:163
    #30 0x10df523b4 in shell_exec shell.c:13106
    #31 0x10e0082cc in runOneSqlLine shell.c:20022
    #32 0x10df56ab0 in process_input shell.c:20122
    #33 0x10df1a19f in main shell.c:20906
    #34 0x7fff71b79cc8 in start (libdyld.dylib:x86_64+0x1acc8)

Address 0x7ffee1d00788 is located in stack of thread T0 at offset 8 in frame
    #0 0x10e76d5ff in duckdb::Binder::PlanFilter(std::__1::unique_ptr<duckdb::Expression, std::__1::default_delete<duckdb::Expression> >, std::__1::unique_ptr<duckdb::LogicalOperator, std::__1::default_delete<duckdb::LogicalOperator> >) plan_select_node.cpp:11
```

Seems this only happens when "create view" (not create table" && contains "IN" or "NOT IN".

**Comment by Mytherin** [comment]
I can confirm that this segfaults. Thanks for the report! Will investigate.
