### ISSUE TITLE
Fix 32 Bit Tests

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#255]
There is an intermittent issue with 32 Bit Linux, also on ARM. Possible culprit is the Value() constructor, see here:

````
==6385==ERROR: AddressSanitizer: stack-use-after-scope on address 0xbe8ffa20 at pc 0xb5e9eddc bp 0xbe8ff97c sp 0xbe8ff968
WRITE of size 1 at 0xbe8ffa20 thread T0
    #0 0xb5e9eddb in duckdb::Value::Value(duckdb::Value const&) duckdb/src/common/types/value.cpp:22
    #1 0xb5d81327 in std::unique_ptr<duckdb::ConstantExpression, std::default_delete<duckdb::ConstantExpression> > duckdb::make_unique<duckdb::ConstantExpression, duckdb::SQLType, duckdb::Value>(duckdb::SQLType&&, duckdb::Value&&) duckdb/src/include/common/helper.hpp:24
    #2 0xb5d71fa3 in duckdb::Transformer::TransformValue(postgres::Value) duckdb/src/parser/transform/expression/transform_constant.cpp:12
    #3 0xb5d72f0f in duckdb::Transformer::TransformConstant(postgres::A_Const*) duckdb/src/parser/transform/expression/transform_constant.cpp:38
````

**Comment by hannesmuehleisen** [comment]
seems fixed
