### ISSUE TITLE
Transformer segfault on t.*

### ISSUE THREAD

**Issue by mclements** [cwida/duckdb#415]
Congratulations on the very nice database.

I found the following bug in DuckDB 67942f96 that leads to a segfault. The issue seems to be related to `t1.*`.

```
create table r4 (i int, j int);
insert into r4 (i, j) values (1,1), (1,2), (1,3), (1,4), (1,5);
select t1.i, t1.j as a, t2.j as b from r4 t1 inner join r4 t2 using(i,j); -- okay
select t1.i, t1.j as a, t2.j as b from r4 t1 inner join r4 t2 on t1.i=t2.i and t1.j=t2.j; -- okay
select t1.*, t2.j b from r4 t1 inner join r4 t2 using(i,j); -- segfaults
select t1.*, t2.j b from r4 t1 inner join r4 t2 on t1.i=t2.i and t1.j=t2.j; -- segfaults
```

Sincerely, Mark.

**Comment by mclements** [comment]
As additional information, this was on Ubuntu 18.04 on an amd64 architecture. The gdb trace from duckdb_cli was:

```
sqlite> .read /home/marcle/work/duckdb_bug.sql
1|1|1
1|2|2
1|3|3
1|4|4
1|5|5
1|1|1
1|2|2
1|3|3
1|4|4
1|5|5

Program received signal SIGSEGV, Segmentation fault.
__strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
62	../sysdeps/x86_64/multiarch/strlen-avx2.S: No such file or directory.
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x0000555555826bc0 in duckdb::Transformer::TransformColumnRef(PGColumnRef*) ()
#2  0x0000555555829f85 in duckdb::Transformer::TransformExpression(PGNode*) ()
#3  0x000055555582aa67 in duckdb::Transformer::TransformResTarget(PGResTarget*) ()
#4  0x0000555555829ef5 in duckdb::Transformer::TransformExpression(PGNode*) ()
#5  0x000055555582acfb in duckdb::Transformer::TransformExpressionList(PGList*, std::vector<std::unique_ptr<duckdb::ParsedExpression, std::default_delete<duckdb::ParsedExpression> >, std::allocator<std::unique_ptr<duckdb::ParsedExpression, std::default_delete<duckdb::ParsedExpression> > > >&) ()
#6  0x00005555557c5453 in duckdb::Transformer::TransformSelectNode(PGSelectStmt*) ()
#7  0x00005555557c6c73 in duckdb::Transformer::TransformSelect(PGNode*) ()
#8  0x000055555572ec9d in duckdb::Transformer::TransformStatement(PGNode*) ()
#9  0x000055555572ed1e in duckdb::Transformer::TransformStatement(PGNode*) ()
#10 0x000055555572eece in duckdb::Transformer::TransformParseTree(PGList*, std::vector<std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> >, std::allocator<std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> > > >&) ()
#11 0x000055555572da7a in duckdb::Parser::ParseQuery(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#12 0x00005555556b88ab in duckdb::Connection::ExtractStatements(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
#13 0x000055555562626a in sqlite3_prepare_v2 ()
#14 0x00005555556179d0 in shell_exec ()
#15 0x0000555555618edb in runOneSqlLine ()
#16 0x000055555561fa2b in process_input ()
#17 0x000055555561b751 in do_meta_command ()
#18 0x000055555561f7b6 in process_input ()
#19 0x0000555555605422 in main ()
```

-- Mark

**Comment by hannesmuehleisen** [comment]
Confirmed, also segfaults on OSX
