### ISSUE TITLE
UPDATE causes subsequent query to segfault

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#534]
Consider the following statements:

```sql
CREATE TABLE t0(c0 VARCHAR, c1 DOUBLE UNIQUE);
INSERT INTO t0(c0) VALUES (NULL);
UPDATE t0 SET c0=0;
INSERT INTO t0(c0, c1) VALUES (0, 0);
SELECT * FROM t0 WHERE 1 > c1; -- Segmentation fault
```
Unexpectedly, the `SELECT` results in a segfault when using the release build. When using the debug build, ASan prints the following:
```
==23602==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x55c62ae5bc92 bp 0x7ffd7930f710 sp 0x7ffd7930f6f0 T0)
==23602==The signal is caused by a READ memory access.
==23602==Hint: address points to the zero page.
    #0 0x55c62ae5bc91 in duckdb::Utf8Proc::Analyze(char const*, unsigned long) /duckdb/third_party/utf8proc/utf8proc_wrapper.cpp:27
    #1 0x55c62a19606a in duckdb::string_t::Verify() /duckdb/src/common/types/string_type.cpp:13
    #2 0x55c62a1ac8c2 in duckdb::Vector::Verify(duckdb::SelectionVector const&, unsigned long) /duckdb/src/common/types/vector.cpp:609
    #3 0x55c62a1ad01d in duckdb::Vector::Verify(unsigned long) /duckdb/src/common/types/vector.cpp:655
    #4 0x55c62a18f918 in duckdb::DataChunk::Verify() /duckdb/src/common/types/data_chunk.cpp:183
    #5 0x55c62a43f1f2 in duckdb::PhysicalOperator::GetChunk(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/physical_operator.cpp:48
    #6 0x55c62aae9166 in duckdb::PhysicalFilter::GetChunkInternal(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/operator/filter/physical_filter.cpp:39
    #7 0x55c62a43f1d3 in duckdb::PhysicalOperator::GetChunk(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/physical_operator.cpp:45
    #8 0x55c62ab1937e in duckdb::PhysicalProjection::GetChunkInternal(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/operator/projection/physical_projection.cpp:22
    #9 0x55c62a43f1d3 in duckdb::PhysicalOperator::GetChunk(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/physical_operator.cpp:45
    #10 0x55c62aae9fc6 in duckdb::PhysicalExecute::GetChunkInternal(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/operator/helper/physical_execute.cpp:8
    #11 0x55c62a43f1d3 in duckdb::PhysicalOperator::GetChunk(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) /duckdb/src/execution/physical_operator.cpp:45
    #12 0x55c62a48bddf in duckdb::ClientContext::FetchInternal() /duckdb/src/main/client_context.cpp:153
    #13 0x55c62a48d67a in duckdb::ClientContext::ExecutePreparedStatement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, duckdb::PreparedStatementData&, std::vector<duckdb::Value, std::allocator<duckdb::Value> >, bool) /duckdb/src/main/client_context.cpp:232
    #14 0x55c62a48ff61 in duckdb::ClientContext::RunStatementInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> >, bool) /duckdb/src/main/client_context.cpp:333
    #15 0x55c62a4908e7 in duckdb::ClientContext::RunStatement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> >, bool) /duckdb/src/main/client_context.cpp:360
    #16 0x55c62a48f367 in duckdb::ClientContext::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) /duckdb/src/main/client_context.cpp:304
    #17 0x55c62a4a7db5 in duckdb::PreparedStatement::Execute(std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, bool) /duckdb/src/main/prepared_statement.cpp:37
    #18 0x55c62a16afed in sqlite3_step /duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:195
    #19 0x55c62a145077 in exec_prepared_stmt /duckdb/tools/shell/shell.c:10135
    #20 0x55c62a146e57 in shell_exec /duckdb/tools/shell/shell.c:10434
    #21 0x55c62a16023d in runOneSqlLine /duckdb/tools/shell/shell.c:15341
    #22 0x55c62a160b77 in process_input /duckdb/tools/shell/shell.c:15442
    #23 0x55c62a163284 in main /duckdb/tools/shell/shell.c:16107
    #24 0x7f0ffc01db6a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26b6a)
    #25 0x55c62a120669 in _start (/duckdb/build/debug/duckdb_cli+0x891669)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /duckdb/third_party/utf8proc/utf8proc_wrapper.cpp:27 in duckdb::Utf8Proc::Analyze(char const*, unsigned long)
==23602==ABORTING
```
I found this based on the latest commit on master (3f0eb5134512c6097805998ccc5eb44476534736).

**Comment by Mytherin** [comment]
Fixed this one in 1866e91805ddcc6ac0e0236d44209325334524e4, the issue was that the value was that a string value was not properly fetched when doing an index lookup when there was an update present on another value in the table. Very nice find :)
