### ISSUE TITLE
A negative DATE results in a "double free or corruption" crash

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#587]
Consider the following statement:
```sql
SELECT DATE '-10000-01-01'; -- double free or corruption
```
Unexpectedly, the `SELECT` results in a `double free or corruption` crash. I found this based on commit dc352a3729f57252a1f6bfa18077fed9c4598a54.

**Comment by mrigger** [comment]
In debug builds, this causes the following ASan error:
```
==24926==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6210000118ff at pc 0x55f6933c5662 bp 0x7fffe17e8650 sp 0x7fffe17e8640
WRITE of size 1 at 0x6210000118ff thread T0
    #0 0x55f6933c5661 in char* duckdb::StringToIntegerCast::FormatUnsigned<int>(int, char*) duckdb/src/common/operator/cast_operators.cpp:463
    #1 0x55f6933c1fe9 in duckdb::DateToStringCast::Format(char*, int*, unsigned long, bool) (duckdb/build/debug/duckdb_cli+0x105efe9)
    #2 0x55f6933b61ed in duckdb::string_t duckdb::CastFromDate::Operation<int>(int, duckdb::Vector&) duckdb/src/common/operator/cast_operators.cpp:649
    #3 0x55f692d29826 in operator() duckdb/src/common/vector_operations/vector_cast.cpp:17
    #4 0x55f692d3c431 in Operation<string_cast(duckdb::Vector&, duckdb::Vector&, duckdb::idx_t) [with SRC = int; OP = duckdb::CastFromDate]::<lambda(int)>, bool, int, duckdb::string_t> duckdb/src/include/duckdb/common/vector_operations/unary_executor.hpp:29
    #5 0x55f692d37b27 in ExecuteStandard<int, duckdb::string_t, duckdb::UnaryLambdaWrapper, bool, string_cast(duckdb::Vector&, duckdb::Vector&, duckdb::idx_t) [with SRC = int; OP = duckdb::CastFromDate]::<lambda(int)>, true> duckdb/src/include/duckdb/common/vector_operations/unary_executor.hpp:93
    #6 0x55f692d341ca in Execute<int, duckdb::string_t, true, string_cast(duckdb::Vector&, duckdb::Vector&, duckdb::idx_t) [with SRC = int; OP = duckdb::CastFromDate]::<lambda(int)> > duckdb/src/include/duckdb/common/vector_operations/unary_executor.hpp:134
    #7 0x55f692d298d0 in string_cast<int, duckdb::CastFromDate> duckdb/src/common/vector_operations/vector_cast.cpp:16
    #8 0x55f692d222ce in date_cast_switch duckdb/src/common/vector_operations/vector_cast.cpp:144
    #9 0x55f692d23432 in duckdb::VectorOperations::Cast(duckdb::Vector&, duckdb::Vector&, duckdb::SQLType, duckdb::SQLType, unsigned long) duckdb/src/common/vector_operations/vector_cast.cpp:226
    #10 0x55f692cdc634 in duckdb::Value::CastAs(duckdb::SQLType, duckdb::SQLType) duckdb/src/common/types/value.cpp:519
    #11 0x55f692c9fd66 in sqlite3_column_has_value duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:400
    #12 0x55f692ca085e in sqlite3_column_text duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:433
    #13 0x55f692c783e1 in exec_prepared_stmt duckdb/tools/shell/shell.c:9924
    #14 0x55f692c79fa7 in shell_exec duckdb/tools/shell/shell.c:10187
    #15 0x55f692c9338d in runOneSqlLine duckdb/tools/shell/shell.c:15047
    #16 0x55f692c93cc7 in process_input duckdb/tools/shell/shell.c:15149
    #17 0x55f692c963d4 in main duckdb/tools/shell/shell.c:15817
    #18 0x7f7e1e285b6a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26b6a)
    #19 0x55f692c537b9 in _start (duckdb/build/debug/duckdb_cli+0x8f07b9)
```
