### ISSUE TITLE
UPDATE results in crash or ASan error

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#599]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT, c1 VARCHAR);
INSERT INTO t0 VALUES (0, 0), (NULL, 0);
UPDATE t0 SET c1 = c0; -- SEGV on unknown address 0x000000000000
```
In the original test case, the `UPDATE` crashed the JVM with a segfault. I reduced the test case based on the debug build, in which the following assertion fails:
```
==27933==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7ff061b980c7 bp 0x7ffe3c2ad770 sp 0x7ffe3c2acee8 T0)
==27933==The signal is caused by a READ memory access.
==27933==Hint: address points to the zero page.
    #0 0x7ff061b980c6  (/lib/x86_64-linux-gnu/libc.so.6+0x1860c6)
    #1 0x7ff061fcecab  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x66cab)
    #2 0x7ff061ea5eb7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&) (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0x140eb7)
    #3 0x562a4969960a in duckdb::StringSegment::CreateStringUpdate(duckdb::SegmentStatistics&, duckdb::Vector&, long*, unsigned long, unsigned long) duckdb/src/storage/string_segment.cpp:686
    #4 0x562a4969c474 in duckdb::StringSegment::Update(duckdb::ColumnData&, duckdb::SegmentStatistics&, duckdb::Transaction&, duckdb::Vector&, long*, unsigned long, unsigned long, unsigned long, duckdb::UpdateInfo*) duckdb/src/storage/string_segment.cpp:801
    #5 0x562a49689ad0 in duckdb::UncompressedSegment::Update(duckdb::ColumnData&, duckdb::SegmentStatistics&, duckdb::Transaction&, duckdb::Vector&, long*, unsigned long, long) duckdb/src/storage/uncompressed_segment.cpp:113
    #6 0x562a49beae5c in duckdb::TransientSegment::Update(duckdb::ColumnData&, duckdb::Transaction&, duckdb::Vector&, long*, unsigned long) duckdb/src/storage/table/transient_segment.cpp:54
    #7 0x562a4966efc6 in duckdb::ColumnData::Update(duckdb::Transaction&, duckdb::Vector&, duckdb::Vector&, unsigned long) duckdb/src/storage/column_data.cpp:156
    #8 0x562a496784b0 in duckdb::DataTable::Update(duckdb::TableCatalogEntry&, duckdb::ClientContext&, duckdb::Vector&, std::vector<unsigned long, std::allocator<unsigned long> >&, duckdb::DataChunk&) duckdb/src/storage/data_table.cpp:719
    #9 0x562a49e0be0a in duckdb::PhysicalUpdate::GetChunkInternal(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) duckdb/src/execution/operator/persistent/physical_update.cpp:63
    #10 0x562a4958a87b in duckdb::PhysicalOperator::GetChunk(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) duckdb/src/execution/physical_operator.cpp:45
    #11 0x562a49dd6cb6 in duckdb::PhysicalExecute::GetChunkInternal(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) duckdb/src/execution/operator/helper/physical_execute.cpp:8
    #12 0x562a4958a87b in duckdb::PhysicalOperator::GetChunk(duckdb::ClientContext&, duckdb::DataChunk&, duckdb::PhysicalOperatorState*) duckdb/src/execution/physical_operator.cpp:45
    #13 0x562a495d84fd in duckdb::ClientContext::FetchInternal() duckdb/src/main/client_context.cpp:153
    #14 0x562a495d9d98 in duckdb::ClientContext::ExecutePreparedStatement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, duckdb::PreparedStatementData&, std::vector<duckdb::Value, std::allocator<duckdb::Value> >, bool) duckdb/src/main/client_context.cpp:232
    #15 0x562a495dc751 in duckdb::ClientContext::RunStatementInternal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> >, bool) duckdb/src/main/client_context.cpp:340
    #16 0x562a495dd0d7 in duckdb::ClientContext::RunStatement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<duckdb::SQLStatement, std::default_delete<duckdb::SQLStatement> >, bool) duckdb/src/main/client_context.cpp:367
    #17 0x562a495dbb49 in duckdb::ClientContext::Execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) duckdb/src/main/client_context.cpp:311
    #18 0x562a495f542b in duckdb::PreparedStatement::Execute(std::vector<duckdb::Value, std::allocator<duckdb::Value> >&, bool) duckdb/src/main/prepared_statement.cpp:37
    #19 0x562a492a2810 in sqlite3_step duckdb/tools/sqlite3_api_wrapper/sqlite3_api_wrapper.cpp:195
    #20 0x562a4927c1d7 in exec_prepared_stmt duckdb/tools/shell/shell.c:9899
    #21 0x562a4927dfb7 in shell_exec duckdb/tools/shell/shell.c:10187
    #22 0x562a4929739d in runOneSqlLine duckdb/tools/shell/shell.c:15047
    #23 0x562a49297cd7 in process_input duckdb/tools/shell/shell.c:15149
    #24 0x562a4929a3e4 in main duckdb/tools/shell/shell.c:15817
    #25 0x7ff061a38b6a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x26b6a)
    #26 0x562a492577c9 in _start (duckdb/build/debug/duckdb_cli+0x9067c9)
```
I found this based on commit c0fe270145e2ade0c0bfe38220aca06d2012f2d9.

**Comment by Mytherin** [comment]
Thanks for the report! This was a newly introduced issue by a recent PR. The bug was that string statistics were being updated with string values that were NULL. Since the actual string values are uninitialized when the bitmask contains NULL, this resulted in weird undefined behavior and ASAN errors triggering. I fixed this in 29e801a7a8c1d219f5633b35dca5c88ced20abdd.
