### ISSUE TITLE
String filter not handled with PRAGMA enable_profiling='json'

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#814]
import duckdb
import sys
import duckdb_query_graph

reload(sys)
sys.setdefaultencoding("utf-8")

cursor.execute("PRAGMA enable_profiling='json';")
cursor.execute("PRAGMA profile_output='/tmp/file.json';")

Profiling this statement returns an error
print(cursor.execute("select count(*) from nation join lineitem on n_nationkey= l_linenumber where n_name = 'GERMANY' "));

Profiling this statement does not return an error
print(cursor.execute("select count(*) from nation join lineitem on n_nationkey= l_linenumber where n_regionkey = 3 "));

Entry in html file:    "extra_info": "nation n_name=\x4745524D414E59",

>>> print(cursor.execute("select count(*) from nation join lineitem on n_nationkey= l_linenumber where n_name = 'GERMANY' "));
<duckdb.DuckDBPyConnection object at 0x7f9e943967a0>
>>> 
>>> duckdb_query_graph.generate('/tmp/file.json', '/tmp/file_n_l_filter_n.html')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/j.tommaney/.local/lib/python2.7/site-packages/duckdb_query_graph/__init__.py", line 377, in generate
    parsed_json = json.loads(text)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 46 column 30 (char 1266)

$cat /tmp/file.json
{ "result": 0.913206,
"timings": {
"optimizer": 0.000019,
"optimizer > column_lifetime": 0.000000,
"optimizer > expression_rewriter": 0.000000,
"optimizer > filter_pushdown": 0.000001,
"optimizer > in_clause": 0.000000,
"optimizer > index_scan": 0.000000,
"optimizer > join_order": 0.000001,
"optimizer > regex_range": 0.000000,
"optimizer > reorder_filter_expressions": 0.000004,
"optimizer > top_n": 0.000000,
"optimizer > unused_columns": 0.000000,
"physical_planner": 0.000003,
"physical_planner > column_binding": 0.000000,
"physical_planner > create_plan": 0.000001,
"physical_planner > resolve_types": 0.000000,
"planner": 0.000004,
"planner > binder": 0.000002},
"tree": { "name": "EXECUTE",
"timing":0.00,
"cardinality":0,
"extra_info": "",
"children": [{ "name": "PROJECTION",
"timing":0.00,
"cardinality":0,
"extra_info": "count()\n",
"children": [{ "name": "SIMPLE_AGGREGATE",
"timing":0.00,
"cardinality":0,
"extra_info": "",
"children": [{ "name": "HASH_JOIN",
"timing":0.60,
"cardinality":2140173,
"extra_info": "INNER\nl_linenumber=n_nationkey\n",
"children": [{ "name": "SEQ_SCAN",
"timing":0.21,
"cardinality":59986052,
"extra_info": "lineitem",
"children": []
}
,
{ "name": "SEQ_SCAN",
"timing":0.00,
"cardinality":1,
"extra_info": "nation n_name=\x4745524D414E59",
"children": []
}
]
}
]
}
]
}
]
}
}

**Comment by Mytherin** [comment]
Thanks for the report! I noticed this before indeed. Will have a look.
