### ISSUE TITLE
DuckDB JDBC driver issue in the presence of other JDBC drivers

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#848]
When multiple JDBC drivers are present, it seems that sometimes the DuckDB JDBC driver throws an Exception for a connection string that should have been accepted by another JDBC driver. That is, when using `DriverManager.getConnection()` and using a string that does not start with `jdbc:duckdb:`, since it is expected to be accepted by another JDBC driver, I still sometimes get an exception such as the following (in this instance, the connection string started with `jdbc:h2`):

```
java.sql.SQLException: DuckDB JDBC URL needs to start with 'jdbc:duckdb:'
	at org.duckdb.DuckDBDatabase.<init>(DuckDBDatabase.java:14)
	at org.duckdb.DuckDBDriver.connect(DuckDBDriver.java:32)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at sqlancer.h2.H2Provider.createDatabase(H2Provider.java:92)
	at sqlancer.h2.H2Provider.createDatabase(H2Provider.java:1)
	at sqlancer.Main$DBMSExecutor.run(Main.java:335)
	at sqlancer.Main$2.run(Main.java:501)
	at sqlancer.Main$2.runThread(Main.java:479)
	at sqlancer.Main$2.run(Main.java:469)
```

Do you think that this is some issue caused by the DuckDB JDBC driver? Would more information be helpful to reproduce this?

**Comment by hannesmuehleisen** [comment]
I have an idea

**Comment by hannesmuehleisen** [comment]
See #857, this should be fixed now. Perhaps you can give it a try?

**Comment by mrigger** [comment]
Thanks! I can confirm that this works.
