### ISSUE TITLE
Java library throws an error when trying to open Parquet file

### ISSUE THREAD

**Issue by pavelpenchev** [cwida/duckdb#913]
Hi,

when trying to use DuckDB embedded within Java for reading parquet files, I'm getting the following error
```
Exception in thread "main" java.sql.SQLException: Catalog: Table Function with name parquet_scan does not exist!
	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:73)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:127)
```
I'm using version 0.2.1, do I have to provide something extra to get this working?

Thanks in advance!

**Comment by hannesmuehleisen** [comment]
We need to enable the parquet extension for the JDBC distribution

**Comment by hannesmuehleisen** [comment]
Once the linked PR is merged this should work. It will take till the next release (0.2.2) till this is available through Maven. In the meantime, you can install from source.
