### ISSUE TITLE
CLion JDBC support

### ISSUE THREAD

**Issue by jdahlin** [cwida/duckdb#953]
At least org.duckdb.DuckDBConnection.getCatalog needs to be implemented for it to work:

```
[snip]
Caused by: java.sql.SQLFeatureNotSupportedException
        at org.duckdb.DuckDBConnection.getCatalog(DuckDBConnection.java:164)
        at com.intellij.database.remote.jdba.jdbc.JdbcIntermediateFacade.obtainConnectionInfoFromJdbc(JdbcIntermediateFacade.java:153)
        at com.intellij.database.remote.jdba.jdbc.JdbcIntermediateFacade.getConnectionInfo(JdbcIntermediateFacade.java:134)
        at com.intellij.database.remote.jdba.impl.RemoteFacadeImpl.getConnectionInfo(RemoteFacadeImpl.java:43)
[snip]
```

**Comment by hannesmuehleisen** [comment]
Try the master branch please

**Comment by jdahlin** [comment]
@hannesmuehleisen https://github.com/cwida/duckdb/blob/master/tools/jdbc/src/main/java/org/duckdb/DuckDBConnection.java#L163 is still not implemented. Also, even if it was, I'm unable to successfully compile the jar locally. Would be good if the artifacts could be extracted from Travis jobs..

**Comment by hannesmuehleisen** [comment]
Ah I see will add. Binaries from master are here: https://github.com/cwida/duckdb/releases/tag/master-builds

**Comment by hannesmuehleisen** [comment]
We merged a fix for this, tried with CLion on my Mac and everything seems to work
