### ISSUE TITLE
Getting a query plan using JDBC

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#958]
I would like to obtain a textual representation of the query plan for a query using JDBC. I tried sending a query prefixed by `EXPLAIN` using the `Statement.executeQuery` method (which seems to work for SQLite), but this results in the following error:

```
Caused by: java.sql.SQLException: executeQuery() can only be used with SELECT queries
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:98)
	at org.duckdb.DuckDBPreparedStatement.executeQuery(DuckDBPreparedStatement.java:128)
```
Is there any way to obtain a query plan string?

**Comment by hannesmuehleisen** [comment]
Clearly this is a bug
